siteTitle="MyGi"
siteDescription="MyGi App companion website and home of the unofficial Glycemic Index Food List"
linkPrefix=""
noProductionJavascript=false
baseUrl="https://mygi.io"
appIcon="https://mygi.io/mygi-app-icon.png"
