export const GET_FOODLIST_REQUEST = 'GET_FOODLIST_REQUEST';
export const GET_FOODLIST_SUCCESS = 'GET_FOODLIST_SUCCESS';
export const GET_FOODLIST_ERROR = 'GET_FOODLIST_ERROR';
export const RECEIVE_FOODLIST = 'RECEIVE_FOODLIST';

export const GET_DATASOURCES_REQUEST = 'GET_DATASOURCES_REQUEST';
export const GET_DATASOURCES_SUCCESS = 'GET_DATASOURCES_SUCCESS';
export const GET_DATASOURCES_ERROR = 'GET_DATASOURCES_ERROR';
export const RECEIVE_DATASOURCES = 'RECEIVE_DATASOURCES';
