export const GET_FOODLIST_REQUEST = 'GET_FOODLIST_REQUEST';
export const GET_FOODLIST_SUCCESS = 'GET_FOODLIST_SUCCESS';
export const GET_FOODLIST_ERROR = 'GET_FOODLIST_ERROR';
export const RECEIVE_FOODLIST = 'RECEIVE_FOODLIST';

export const GET_DATASOURCES_REQUEST = 'GET_DATASOURCES_REQUEST';
export const GET_DATASOURCES_SUCCESS = 'GET_DATASOURCES_SUCCESS';
export const GET_DATASOURCES_ERROR = 'GET_DATASOURCES_ERROR';
export const RECEIVE_DATASOURCES = 'RECEIVE_DATASOURCES';

export const POST_ASSOCIATE_DATASOURCE_REQUEST = 'POST_ASSOCIATE_DATASOURCE_REQUEST';
export const POST_ASSOCIATE_DATASOURCE_SUCCESS = 'POST_ASSOCIATE_DATASOURCE__SUCCESS';
export const POST_ASSOCIATE_DATASOURCE_ERROR = 'POST_ASSOCIATE_DATASOURCE__ERROR';

export const DELETE_ASSOCIATED_DATASOURCE_REQUEST = 'DELETE_ASSOCIATED_DATASOURCE_REQUEST';
export const DELETE_ASSOCIATED_DATASOURCE_SUCCESS = 'DELETE_ASSOCIATED_DATASOURCE__SUCCESS';
export const DELETE_ASSOCIATED_DATASOURCE_ERROR = 'DELETE_ASSOCIATED_DATASOURCE__ERROR';
